name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ruby and Bundle Install
        uses: eregon/use-ruby-action@v1

        with:
          bundler-cache: true

      - name: Spec
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}

        run: bundle exec rspec
